# Generated by Django 5.1 on 2025-04-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_employer_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="skills",
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="skills",
            field=models.ManyToManyField(blank=True, to="accounts.skill"),
        ),
    ]
