# Generated by Django 5.1 on 2025-03-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_experience_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                help_text="FontAwesome icon class (e.g., 'fas fa-code')", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("entry", "Entry Level"),
                    ("junior", "Junior"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior"),
                    ("lead", "Team Lead"),
                    ("manager", "Manager"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
