# Generated by Django 5.1 on 2025-03-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_category_icon_alter_job_experience_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("intern", "Intern/Fresher"),
                    ("entry", "Entry Level"),
                    ("junior", "Junior"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior"),
                    ("lead", "Team Lead"),
                    ("manager", "Manager"),
                ],
                max_length=20,
            ),
        ),
    ]
